[tool.pytest.ini_options]
log_cli = false
log_cli_level = "INFO"
log_cli_format = "%(message)s"

log_file = "./logs/churn_library.log"
log_file_level = "INFO"
log_file_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_file_date_format = "%Y-%m-%d %H:%M:%S"
